apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: logging-composition
spec:
  mode: Pipeline
  resources:
    - name: Logging
      base: 
        apiVersion: logging.banzaicloud.io/v1beta1
        kind: Logging
        spec:
          controlNamespace: ""
          fluentd:
            disablePvc: true
  compositeTypeRef:
    apiVersion: caas.telekom.de/v1alpha1
    kind: XLogging
  pipeline:
  - step: get-labels
    functionRef:
      name: logging-labeler
    input: {}
      
